#!/usr/bin/python3

"""
@ /favicon.ico
    Set what the media type will be in the autogenerated OpenAPI specification.
    fastapi.tiangolo.com/advanced/additional-responses/#additional-media-types-for-the-main-response

    Prevent FastAPI from adding "application/json" as an additional
    response media type in the autogenerated OpenAPI specification.
    https://github.com/tiangolo/fastapi/issues/3258
"""


from typing import Union

import uvicorn

from fastapi import FastAPI, Response
from fastapi.middleware.cors import CORSMiddleware
origins = ["*"]

app = FastAPI()


@app.get("/")
def read_root():
    return {"name": "World"}

@app.get(
    "/favicon.ico",


    responses = {
        200: {
            "content": {"image/png": {}}
        }
    },

    
    response_class=Response
)
def get_image():
    image_bytes: bytes = b""

    with open('favicon.ico', 'rb') as file:
        image_bytes = file.read()
        file.close()

    return Response(content=image_bytes, media_type="image/png")

@app.get("/items/{item_id}")
def read_item(item_id: int, q: Union[str, None] = None):
    return {"item_id": item_id, "q": q}


uvicorn.run(app, host="0.0.0.0", port=5000)